# Generated by Django 5.0.3 on 2024-04-15 13:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('g_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('g_name', models.CharField(blank=True, max_length=50)),
                ('g_desc', models.CharField(blank=True, max_length=100)),
                ('g_category', models.CharField(choices=[('E-SABONG', 'E-SABONG'), ('BALL GAMES', 'BALL GAMES')], max_length=50, null=True)),
                ('g_link', models.CharField(blank=True, max_length=100)),
                ('g_image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('g_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fight',
            fields=[
                ('f_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('f_number', models.IntegerField(blank=True, null=True)),
                ('f_wala_odd', models.IntegerField(blank=True, null=True)),
                ('f_meron_odd', models.IntegerField(blank=True, null=True)),
                ('f_walatotalbet', models.IntegerField(blank=True, null=True)),
                ('f_merontotalbet', models.IntegerField(blank=True, null=True)),
                ('f_winner', models.CharField(blank=True, max_length=100)),
                ('f_status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSE'), ('DONE', 'DONE')], max_length=50, null=True)),
                ('f_update', models.DateTimeField(auto_now=True)),
                ('f_created', models.DateTimeField(auto_now_add=True)),
                ('f_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_game', to='ugs_app.games')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(blank='00000000000', max_length=11, null=True)),
                ('usertype', models.CharField(choices=[('SUPER ADMIN', 'SUPER ADMIN'), ('ADMIN', 'ADMIN'), ('DECLARATOR', 'DECLARATOR'), ('LOADER', 'LOADER'), ('AGENT', 'AGENT'), ('PLAYER', 'PLAYER')], max_length=50)),
                ('referral_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('BANNED', 'BANNED')], default='ACTIVE', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('w_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('w_balance', models.IntegerField(blank=True, null=True)),
                ('w_points', models.IntegerField(blank=True, null=True)),
                ('w_commission', models.IntegerField(blank=True, null=True)),
                ('w_status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('BANNED', 'BANNED')], max_length=50)),
                ('w_dateupdate', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
