# Generated by Django 5.0.3 on 2024-03-15 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=50)),
                ('user_password', models.CharField(blank=True, max_length=50)),
                ('contact_no', models.IntegerField(blank=True, null=True)),
                ('usertype', models.CharField(choices=[('SUPER ADMIN', 'SUPER ADMIN'), ('ADMIN', 'ADMIN'), ('DECLARATOR', 'DECLARATOR'), ('LOADER', 'LOADER'), ('AGENT', 'AGENT'), ('PLAYER', 'PLAYER')], max_length=50)),
                ('referral_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('BANNED', 'BANNED')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
