# Generated by Django 5.0.3 on 2024-03-15 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0003_useraccount_user_agent_alter_userwallet_w_dateupdate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwallet',
            old_name='w_user',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='w_dateupdate',
            field=models.TimeField(default=datetime.time(17, 51, 59, 981919)),
        ),
    ]
