# Generated by Django 5.0.3 on 2024-03-15 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0004_rename_w_user_userwallet_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='w_dateupdate',
            field=models.TimeField(default=datetime.time(17, 54, 28, 699783)),
        ),
    ]
