# Generated by Django 5.0.3 on 2024-03-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0005_alter_userwallet_w_dateupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='w_dateupdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
