# Generated by Django 5.0.3 on 2024-03-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0006_alter_userwallet_w_dateupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='user_password',
        ),
    ]
