# Generated by Django 5.0.3 on 2024-03-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0010_alter_useraccount_user_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='status',
        ),
    ]
