# Generated by Django 5.0.3 on 2024-03-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0014_alter_useraccount_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
