# Generated by Django 5.0.3 on 2024-03-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0015_alter_useraccount_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='user',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_wallet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to='ugs_app.userwallet'),
        ),
    ]
