# Generated by Django 5.0.3 on 2024-03-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0018_alter_useraccount_user_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwallet',
            old_name='user',
            new_name='w_user',
        ),
    ]
