# Generated by Django 5.0.3 on 2024-03-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0019_rename_user_userwallet_w_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwallet',
            old_name='w_user',
            new_name='user',
        ),
    ]
