# Generated by Django 5.0.3 on 2024-03-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0020_rename_w_user_userwallet_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_wallet',
        ),
    ]
