# Generated by Django 5.0.3 on 2024-03-28 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugs_app', '0022_useraccount_status_alter_userwallet_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('g_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('g_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
